version: '3.0'
services:
  json-server:
    image: vimagick/json-server
    command: --host 0.0.0.0 --port 8080 -w /config/db.json
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    restart: always

