name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      json-server:
        image: vimagick/json-server
        ports:
          - 8080:8080
        volumes:
          - ./config/db.json:/config/db.json  # Adjust to ensure db.json is correctly mapped
        options: >-
          --health-cmd="curl --fail http://localhost:8080" 
          --health-interval=5s 
          --health-timeout=3s 
          --health-retries=5
        entrypoint: ["json-server", "--watch", "/config/db.json", "--port", "8080"]  # Use entrypoint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Wait for json-server to be ready
        run: |
          echo "Waiting for json-server to be ready..."
          for i in {1..10}; do
            curl -s http://localhost:8080 && break || sleep 5;
          done

      - name: Run tests
        run: npm test


